[string]
db_types = ["character", "character varying", "text", "money"]
notnull_go_type = "string"
nullable_go_type = "null.String"

[time]
db_types = [
    "time with time zone", "time without time zone", "date"
]
notnull_go_type = "time.Time"
nullable_go_type = "null.Time"

[timestamp]
db_types = [
    "timestamp without time zone", "timestamp with time zone"
]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[bool]
db_types = ["boolean"]
notnull_go_type = "bool"
nullable_go_type = "null.Bool"

[smallint]
db_types = ["smallint"]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[integer]
db_types = ["integer","oid"]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[bigint]
db_types = ["bigint"]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[smallserial]
db_types = ["smallserial"]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[serial]
db_types = ["serial"]
notnull_go_type = "null.Int"
nullable_go_type = "null.Int"

[real]
db_types = ["real"]
notnull_go_type = "null.Float"
nullable_go_type = "null.Float"

[numeric]
db_types = ["numeric", "double precision"]
notnull_go_type = "null.Float"
nullable_go_type = "null.Float"

[bytea]
db_types = ["bytea"]
notnull_go_type = "[]byte"
nullable_go_type = "[]byte"

[json]
db_types = ["json"]
notnull_go_type = "types.JSONText"
nullable_go_type = "types.JSONText"


[jsonb]
db_types = ["jsonb"]
notnull_go_type = "types.JSONText"
nullable_go_type = "types.JSONText"

[xml]
db_types = ["xml"]
notnull_go_type = "types.JSONText"
nullable_go_type = "types.JSONText"

[interval]
db_types = ["interval"]
notnull_go_type = "time.Duration"
nullable_go_type = "*time.Duration"

[default]
db_types = ["*"]
notnull_go_type = "interface{}"
nullable_go_type = "interface{}"
