// Code generated by "stringer -type=CDomain"; DO NOT EDIT.

package cmn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CDomainSys-322]
	_ = x[CDomainSysAdmin-333]
	_ = x[CDomainSysMaintain-366]
	_ = x[CDomainSysUser-377]
	_ = x[CDomainSysAnonymous-388]
	_ = x[CDomainSysPromotion-561]
	_ = x[CDomainSysSale-563]
	_ = x[CDomainSysTrial-566]
	_ = x[CDomainAdmin-567]
	_ = x[CDomainMaintain-569]
	_ = x[CDomainUser-671]
	_ = x[CDomainAnonymous-673]
	_ = x[CDomainPromotion-675]
	_ = x[CDomainSale-677]
	_ = x[CDomainTrial-679]
	_ = x[CDomainQNear-1077]
	_ = x[CDomainQNearAdmin-1079]
	_ = x[CDomainAbilityIdx-1177]
	_ = x[CDomainAbilityIdxAdmin-1179]
	_ = x[CDomainForeseeLab-1277]
	_ = x[CDomainForeseeLabAdmin-1279]
	_ = x[CDomainRecruitMgr-1377]
	_ = x[CDomainRecruitMgrAdmin-1379]
	_ = x[CDomainJXDD-1477]
	_ = x[CDomainJXDDAdmin-1479]
	_ = x[CDomainDonate-1577]
	_ = x[CDomainDonateAdmin-1579]
	_ = x[CDomainXKB-10002]
	_ = x[CDomainXKBAdmin-10004]
	_ = x[CDomainXKBSale-10006]
	_ = x[CDomainXKBSchoolAdmin-10008]
	_ = x[CDomainXKBSchoolStatistics-10010]
	_ = x[CDomainXKBUser-10012]
	_ = x[CDomainXKBPromotion-10016]
	_ = x[CDomainXKBFE-10020]
	_ = x[CDomainXKBBE-10030]
	_ = x[CUserDefaultCreator-1000]
	_ = x[CUserDefaultMaintainer-1000]
	_ = x[CUserDefaultDomainID-333]
}

const _CDomain_name = "CDomainSysCDomainSysAdminCDomainSysMaintainCDomainSysUserCDomainSysAnonymousCDomainSysPromotionCDomainSysSaleCDomainSysTrialCDomainAdminCDomainMaintainCDomainUserCDomainAnonymousCDomainPromotionCDomainSaleCDomainTrialCUserDefaultCreatorCDomainQNearCDomainQNearAdminCDomainAbilityIdxCDomainAbilityIdxAdminCDomainForeseeLabCDomainForeseeLabAdminCDomainRecruitMgrCDomainRecruitMgrAdminCDomainJXDDCDomainJXDDAdminCDomainDonateCDomainDonateAdminCDomainXKBCDomainXKBAdminCDomainXKBSaleCDomainXKBSchoolAdminCDomainXKBSchoolStatisticsCDomainXKBUserCDomainXKBPromotionCDomainXKBFECDomainXKBBE"

var _CDomain_map = map[CDomain]string{
	322:   _CDomain_name[0:10],
	333:   _CDomain_name[10:25],
	366:   _CDomain_name[25:43],
	377:   _CDomain_name[43:57],
	388:   _CDomain_name[57:76],
	561:   _CDomain_name[76:95],
	563:   _CDomain_name[95:109],
	566:   _CDomain_name[109:124],
	567:   _CDomain_name[124:136],
	569:   _CDomain_name[136:151],
	671:   _CDomain_name[151:162],
	673:   _CDomain_name[162:178],
	675:   _CDomain_name[178:194],
	677:   _CDomain_name[194:205],
	679:   _CDomain_name[205:217],
	1000:  _CDomain_name[217:236],
	1077:  _CDomain_name[236:248],
	1079:  _CDomain_name[248:265],
	1177:  _CDomain_name[265:282],
	1179:  _CDomain_name[282:304],
	1277:  _CDomain_name[304:321],
	1279:  _CDomain_name[321:343],
	1377:  _CDomain_name[343:360],
	1379:  _CDomain_name[360:382],
	1477:  _CDomain_name[382:393],
	1479:  _CDomain_name[393:409],
	1577:  _CDomain_name[409:422],
	1579:  _CDomain_name[422:440],
	10002: _CDomain_name[440:450],
	10004: _CDomain_name[450:465],
	10006: _CDomain_name[465:479],
	10008: _CDomain_name[479:500],
	10010: _CDomain_name[500:526],
	10012: _CDomain_name[526:540],
	10016: _CDomain_name[540:559],
	10020: _CDomain_name[559:571],
	10030: _CDomain_name[571:583],
}

func (i CDomain) String() string {
	if str, ok := _CDomain_map[i]; ok {
		return str
	}
	return "CDomain(" + strconv.FormatInt(int64(i), 10) + ")"
}
