// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Status struct {
	Code     int     `json:"code"`
	Msg      *string `json:"msg,omitempty"`
	Data     *string `json:"data,omitempty"`
	RowCount *int    `json:"rowCount,omitempty"`
	API      *string `json:"api,omitempty"`
	Method   *string `json:"method,omitempty"`
	Sn       *string `json:"sn,omitempty"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Addi *string `json:"addi,omitempty"`
}

type InputUser struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Cert *string `json:"cert,omitempty"`
	Addi *string `json:"addi,omitempty"`
}
